# -*- coding: utf-8 -*-
"""Lab 1 Nguyễn Đức Nguyên Phúcipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zfvrwRmFHjoDOabIfqMAs4nHogJFYvn
"""

!ls

"""### Set up the Hadoop environment in Colab

"""

!wget https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz

!tar -xzvf hadoop-3.4.1.tar.gz

!java -version

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["HADOOP_HOME"] = "/content/hadoop-3.4.1"

!echo $JAVA_HOME

!rm -rf hadoop-3.4.1.tar.hz

# Commented out IPython magic to ensure Python compatibility.
# %cd hadoop-3.4.1/

!bin/hadoop

!bin/hadoop version

!curl https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMBD0225EN-SkillsNetwork/labs/data/data.txt --output data.txt

!ls

!bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-examples-3.4.1.jar wordcount data.txt output

!ls output

!cat output/part-r-00000

